#file: noinspection UndefinedAction,UndefinedParamsPresent

# ------------------------------------------------------------------------------
# 🚀 Deploy Infrastructure Pipeline
#
# This workflow orchestrates deployments across multiple environments:
# Dev, Staging, and Prod.
#
# Trigger:
# - Automatically triggers on push to the main branch.
# - Can be manually triggered via workflow_dispatch.
#
# Each job calls the reusable workflow defined in:
#   .github/workflows/deploy_infrastructure_template.yml
#
# Inputs:
# - ENVIRONMENT_NAME: passed to the reusable workflow to specify the target environment.
#
# Secrets:
# - Secrets are inherited from the repository settings, including credentials and publish profiles.
#
# This structure ensures sequential deployments and clear separation between environments.
# ------------------------------------------------------------------------------

name: Deploy Infrastructure Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev-infrastructure:
    name: Deploy Infrastructure to Dev
    uses: ./.github/workflows/deploy_infrastructure_template.yml
    with:
      ENVIRONMENT_NAME: Dev
    secrets: inherit

  deploy-dev-apps:
    name: Deploy Apps to Dev
    needs: deploy-dev-infrastructure
    uses: ./.github/workflows/deploy_apps_template.yml
    with:
      ENVIRONMENT_NAME: Dev
    secrets: inherit

  deploy-staging-infrastructure:
    name: Deploy Infrastructure to Staging
    needs: deploy-dev-apps
    uses: ./.github/workflows/deploy_infrastructure_template.yml
    with:
      ENVIRONMENT_NAME: Staging
    secrets: inherit

  deploy-staging-apps:
    name: Deploy Apps to Staging
    needs: deploy-staging-infrastructure
    uses: ./.github/workflows/deploy_apps_template.yml
    with:
      ENVIRONMENT_NAME: Staging
    secrets: inherit

  deploy-prod-infrastructure:
    name: Deploy Infrastructure to Prod
    needs: deploy-staging-apps
    uses: ./.github/workflows/deploy_infrastructure_template.yml
    with:
      ENVIRONMENT_NAME: Prod
    secrets: inherit

  deploy-prod-apps:
    name: Deploy Apps to Prod
    needs: deploy-prod-infrastructure
    uses: ./.github/workflows/deploy_apps_template.yml
    with:
      ENVIRONMENT_NAME: Prod
    secrets: inherit
