#file: noinspection UndefinedParamsPresent

# ------------------------------------------------------------------------------
# ⚙️ Run Bicep Template and Deploy Infrastructure
#
# This workflow is designed as a reusable pipeline for deploying Azure infrastructure
# using Bicep templates.
#
# Setup Notes:
# - The service principal used must have the appropriate permissions configured. Check README.MD:
#
# Triggers:
# - workflow_call: This is intended to be called by other workflows with
#   the required ENVIRONMENT_NAME input.
#
# Inputs:
# - ENVIRONMENT_NAME: Target environment (e.g., Dev, Staging, Prod) to deploy infrastructure.
#
#-------------------------------------------------------------------------------

name: Run Bicep template and deploy infrastructure

on:
  workflow_call:
    inputs:
      ENVIRONMENT_NAME:
        required: true
        type: string
        default: "Dev"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Set GitHub environment
    # Used to set guards for the different environments
    # The environment can be readded if needed.
    # It should be added if a guard needs to take effect regarding deployment.
    # environment: ${{ inputs.ENVIRONMENT_NAME }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # vars can only be defined in a single step
      - name: Set environment variables
        id: vars
        run: |
          ENVIRONMENT_NAME="${{ inputs.ENVIRONMENT_NAME != '' && inputs.ENVIRONMENT_NAME || 'Dev' }}"
          echo "ENVIRONMENT_NAME=$ENVIRONMENT_NAME" >> $GITHUB_OUTPUT
          echo "RESOURCE_GROUP=DotNetFileService-API-$ENVIRONMENT_NAME" >> $GITHUB_OUTPUT

      - name: Uninstall Azure CLI and install specific version
        shell: bash
        run: |
          brew uninstall azure-cli || true
          pip3 install azure-cli==2.72.0

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Create Resource Group With AZ CLI
        run: |
          az deployment sub create \
            --location swedencentral \
            --template-file ./deploy/bicep/modules/createResourceGroup.bicep \
            --parameters environmentName=${{ steps.vars.outputs.ENVIRONMENT_NAME }} \
            --only-show-errors \
            --output none

      - name: Deploy Bicep
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          region: swedencentral
          resourceGroupName: ${{ steps.vars.outputs.RESOURCE_GROUP }}
          template: ./deploy/bicep/main.bicep
          parameters: environmentName=${{ steps.vars.outputs.ENVIRONMENT_NAME }}
